import { AppState, BooksDetails, Doc, EbookAccess, Type } from "../interfaces";

export const initializedEbookAccessState: EbookAccess = {
  Borrowable: "",
  NoEbook: "",
  Printdisabled: "",
  Public: "",
};

export const initializedTypeState: Type = {
  Work: "",
};

export const initilaizedDocState: Doc = {
  key: "",
  type: initializedTypeState,
  seed: "",
  title: "",
  title_suggest: "",
  edition_count: null,
  edition_key: "",
  publish_date: "",
  publish_year: null,
  first_publish_year: null,
  isbn: "",
  last_modified_i: null,
  ebook_count_i: null,
  ebook_access: initializedEbookAccessState,
  has_fulltext: false,
  public_scan_b: false,
  publisher: "",
  language: "",
  author_key: "",
  author_name: "",
  publisher_facet: "",
  _version_: null,
  author_facet: "",
  number_of_pages_median: null,
  cover_edition_key: "",
  cover_i: null,
  lccn: "",
  publish_place: "",
  lcc: "",
  ddc: "",
  ia: "",
  ia_collection_s: "",
  lending_edition_s: "",
  lending_identifier_s: "",
  printdisabled_s: "",
  subject: "",
  id_goodreads: "",
  id_librarything: "",
  ia_box_id: "",
  subject_facet: "",
  lcc_sort: "",
  subject_key: "",
  ddc_sort: "",
  oclc: "",
  author_alternative_name: "",
  ia_collection: "",
  contributor: "",
  subtitle: "",
  person: "",
  place: "",
  id_amazon: "",
  id_overdrive: "",
  person_key: "",
  place_key: "",
  person_facet: "",
  place_facet: "",
  first_sentence: "",
  ia_loaded_id: "",
  time: "",
  time_facet: "",
  time_key: "",
  id_alibris_id: "",
  id_better_world_books: "",
  id_google: "",
  id_hathi_trust: "",
  id_isfdb: "",
  id_librivox: "",
  id_project_gutenberg: "",
  id_standard_ebooks: "",
};

export const initializedBookDetailsState: BooksDetails = {
  numFound: null,
  start: null,
  numFoundExact: false,
  docs: [],
  num_found: null,
  q: "",
  offset: null,
};

export const initializedAppState: AppState = {
  bookDetails: initializedBookDetailsState,
  loadingIndicator: false,
};
